### ISSUE TITLE
Right overlay view not showing on MI4

### ISSUE THREAD

**Issue by zhoulujue** [YoKeyword/IndexableStickyListView#1]
在小米4机型上气泡提示不能显示

**Comment by YoKeyword** [comment]
@zhoulujue 是Demo上“选择联系人”气泡不显示吗？我手边只有一台小米2，MIUI7.2的机子，测试正常。
能报给我MIUI的版本吗？

**Comment by zhoulujue** [comment]
![device-2016-04-05-105516](https://cloud.githubusercontent.com/assets/2437375/14270069/f34aff86-fb1c-11e5-9f10-dc367221af3d.png)

其他机器上都是可以的，就是这一台小米4不行。

**Comment by YoKeyword** [comment]
好哒 我找找手机测试下哈 :)

**Comment by YoKeyword** [comment]
@zhoulujue 解决啦，5.0以下的tint 不能正确执行的问题， 我把TextView换成了AppcompatTextView 可以正常着色了 :)

**Comment by zhoulujue** [comment]
赞👍
