### ISSUE TITLE
error in build.gradle

### ISSUE THREAD

**Issue by Sysmain** [YoKeyword/IndexableStickyListView#10]

**Comment by YoKeyword** [comment]
@Sysmain 你可能需要配置下build.gradle～  检查是否有相应版本的插件等信息  可以替换成自己的版本 或者去更新下载～

**Comment by Sysmain** [comment]
@YoKeyword in app/build.gradle,多了一个花括号（Line 10-11）

**Comment by YoKeyword** [comment]
@Sysmain 非常感谢🙏 ～  下次这种情况可以欢迎提PR哈～
