### ISSUE TITLE
请问搜索的匹配规则如何更改？

### ISSUE THREAD

**Issue by Lsy1992** [YoKeyword/IndexableStickyListView#16]
例如现在demo中对联系人的搜索是匹配中文名称及拼音，若是想增加一项匹配手机号的搜索，应当去何处调整代码？

**Comment by YoKeyword** [comment]
这部分内容在[这个位置的代码](https://github.com/YoKeyword/IndexableStickyListView/blob/master/indexablelistview/src/main/java/me/yokeyword/indexablelistview/IndexBar.java#L288)
可以从这个地方着手～
