### ISSUE TITLE
不好意思又提个问题，请问如果不继承IndexEntity的话，如何在联系人列表中实现让“#”的索引处于最底部？而不是在第一个

### ISSUE THREAD

**Issue by Lsy1992** [YoKeyword/IndexableStickyListView#18]

**Comment by YoKeyword** [comment]
😔 需要自己修改下 排序算法 了～   

不过这个建议我收下了，因为回头闲下来会再维护这个库～
未来更新内容： 使用RecyclerView代替，因为ListView的一些方法导致实现的粘性header代码复杂，回头重点重构，提供更多开放的API供使用～

**Comment by Lsy1992** [comment]
厉害了我的哥

**Comment by YoKeyword** [comment]
😂 ～  感谢建议了哈～
