### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by colinnj** [YoKeyword/IndexableStickyListView#2]
我在使用过程中，重新切换刷新到IndexableStickyListView时，右边快速字母会多出很多重复项

**Comment by YoKeyword** [comment]
@colinnj 是何种情况的刷新？能详细描述吗，我排查下

**Comment by colinnj** [comment]
您有联系方式吗？这个好像传不了图片，或者您加我一下。261314544

**Comment by YoKeyword** [comment]
fixed
