### ISSUE TITLE
字母索引Bar的问题

### ISSUE THREAD

**Issue by wxmylife** [YoKeyword/IndexableStickyListView#3]
如果我不想自动生成字母索引Bar，直接显示标准索引，这个问题该怎么解决呢？

**Comment by YoKeyword** [comment]
@wxmylife  是不显示Bar吗？  标准索引是指什么意思？汉字索引？

**Comment by YoKeyword** [comment]
@wxmylife 如果想隐藏字母索引Bar，你可以调用
`indexableStickyListView.getIndexBar().setVisibility(View.INVISIBLE);`
(这里不要调用GONE，我刚才发现用GONE的话StickyHeaderView显示会有点问题，等我有空修复下哈)
:)

**Comment by wxmylife** [comment]
我的意思是 因为现在是根据数据源自动生成字母索引，现在如果我不想根据数据源去自动生成索引，而是没有数据也显示A-Z#，这个怎么搞？

**Comment by YoKeyword** [comment]
@wxmylife 哦 这个意思啊，这个库目前还不支持这个，当时出发点是自动生成字母索引。
你可以从IndexBar类里的mIndex这个字段出发修改下，这个字段是一个存字母索引的List    :)

**Comment by wxmylife** [comment]
好的  谢谢


来自 魅蓝 note 2
