### ISSUE TITLE
多音字的问题

### ISSUE THREAD

**Issue by ChineseLincoln** [YoKeyword/IndexableStickyListView#4]
比如 重庆、长安 就会出现 C开头 和 Z 开头 怎么能正确的识别多音字？

**Comment by YoKeyword** [comment]
@ChineseLincoln 我下午会push一个commit 提供一个方案解决该问题  :)

**Comment by YoKeyword** [comment]
@ChineseLincoln 已经push，使用方法看下README的第4点，或者直接查看demo的string.xml文件
感谢你的反馈 :)

**Comment by ChineseLincoln** [comment]
thanks
