### ISSUE TITLE
找不到setSupportBackgroundTintList这个方法

### ISSUE THREAD

**Issue by kangyang1024** [YoKeyword/IndexableStickyListView#5]
mTvRightOverlay.setSupportBackgroundTintList(ColorStateList.valueOf(color))
![](http://ww2.sinaimg.cn/large/a7eb544fgw1f4i2ff8gscj20mz09bgpe.jpg)

**Comment by YoKeyword** [comment]
@kangyang1024 这个方法是V7包里AppCompatTextView的方法，23.1.1-23.3都是应该有的

**Comment by kangyang1024** [comment]
额，readme只说要加v7包，我用的是23.0.1版本的。
建议这种样式的设置尽量用android自带的库的api来实现吧。

**Comment by YoKeyword** [comment]
@kangyang1024 这里是给TextView设置的Background，自带的API不能向下兼容；也是能做到的，外面包一层FrameLayout，子View由ImageView和TextView组成，当时觉得麻烦，就不直接用的AppCompatTextView，没想到23.0.1的没这个方法 囧～

要不你先升下23.1 ？  我这边最近正在维护Fragmentation的库，一个比较大的版本更新...

**Comment by kangyang1024** [comment]
ok啦，就是给你反馈一下。

**Comment by YoKeyword** [comment]
@kangyang1024 非常感谢哈 🙏   🙏
